name: Python Syntax Check and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  syntax_check_and_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install -r Sunrise-Cloudy-Weather/requirements.txt  # Install project-specific dependencies
      working-directory: ./Sunrise-Cloudy-Weather/Sunrise-Cloudy-Weather/requirements.txt

    - name: Run Syntax Check
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      working-directory: ./Sunrise-Cloudy-Weather

    - name: Run Tests
      run: |
        pytest
      working-directory: ./Sunrise-Cloudy-Weather

    - name: Push or Merge if Tests Pass
      if: success()  # Only proceed if all previous steps were successful
      run: |
        git push origin main
