name: main

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Adjust Python version as needed

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file

    - name: Run Tests
      run: |
        pytest  # Replace with the command to run your tests

    - name: Streamlit Test
      run: |
        app.py



