name: CI/CD with Auto-Merge

on:
  push:
    # Define your push event configuration here

  pull_request:
    types:
      - closed

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge:
    name: Merge Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Check PR event
        id: pr
        uses: actions/github-script@v4
        with:
          script: |
            if (github.event.pull_request.merged) {
              core.setOutput('shouldMerge', 'true');
            } else {
              core.setOutput('shouldMerge', 'false');
            }

      - name: Merge Pull Request
        if: steps.pr.outputs.shouldMerge == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --ff-only ${{ github.event.pull_request.head.sha }}
          git push
