name: Auto-Merge Pull Request

on:
  pull_request:
    types:
      - closed

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR event
      id: pr
      uses: actions/github-script@v4
      with:
        script: |
          if (github.event.pull_request.merged) {
            core.setOutput('shouldMerge', 'true');
          } else {
            core.setOutput('shouldMerge', 'false');
          }

    - name: Merge Pull Request
      if: steps.pr.outputs.shouldMerge == 'true'
      run: |
        git config user.name "Momart25"
        git config user.email "qjgtturaray@tip.edu.ph"
        git checkout ${{ github.event.pull_request.base.ref }}
        git merge --ff-only ${{ github.event.pull_request.head.sha }}
        git push
