name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge if Super-Linter Passed (for Python)
        if: success() && github.event.repository.language == 'Python'  # Replace with the appropriate language condition
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "Your Name"
          git config user.email "youremail@example.com"
          git checkout main  # Replace 'main' with your target branch
          git merge --ff-only $GITHUB_SHA
          git push
